import React from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import { NextAppDirEmotionCacheProvider } from 'tss-react/next/appDir';
import { Geist, Geist_Mono } from "next/font/google";
import { TssCacheProvider } from "tss-react";
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme/theme';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAppDirEmotionCacheProvider
        options={{ key: "mui" }}
      >
        <NextAppDirEmotionCacheProvider
            options={{ "key": "tss" }}
            CacheProvider={TssCacheProvider}
        >
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <body className={`${geistSans.variable} ${geistMono.variable}`}>
                {children}
              </body>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </NextAppDirEmotionCacheProvider>
      </NextAppDirEmotionCacheProvider >
    </html>
  );
}
