'use client';

import React, { useMemo, useContext, useCallback, createContext } from 'react';
import PropTypes from 'prop-types';
import { useColorScheme, createTheme } from '@mui/material/styles';
// import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import { NextAppDirEmotionCacheProvider } from 'tss-react/next/appDir';
import { Geist, Geist_Mono } from 'next/font/google';
import { TssCacheProvider } from 'tss-react';
import { ThemeProvider, CssBaseline } from '@mui/material';
// import theme from '../theme/theme';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export const AppThemeContext = createContext(null);

export default function RootLayout({ children }) {
  const { mode, setMode } = useColorScheme();
  
  const toggleDarkTheme = useCallback(() => {
    if(mode){
      const currMode = mode === 'dark' ? 'light' : 'dark';
      setMode(currMode);
    }
  },[mode, setMode]);

  // const colorMode = useMemo(() => ({
  //   toggleColorMode: () => {
  //     setMode((prevMode) => (prevMode === 'light' ? 'dark' : 'light'));
  //   }}
  // ),[setMode]);

  const theme = useMemo(
    () =>
      createTheme({
        palette: {
          mode: 'dark',
        },
      }),
    [],
  );

  return (
    <html lang='en'>
      <AppThemeContext.Provider value={null}>
        <NextAppDirEmotionCacheProvider
          options={{ key: 'mui' }}
        >
          <NextAppDirEmotionCacheProvider
            options={{ 'key': 'tss' }}
            CacheProvider={TssCacheProvider}
          >
            <AppRouterCacheProvider options={{enableCssLayer: false}}>
              <ThemeProvider theme={theme}>
                <body className={`${geistSans.variable} ${geistMono.variable}`}>
                  <button onClick={() => toggleDarkTheme()}>
                    Dark Mode Togglexxx
                  </button>
                  {children}
                </body>
              </ThemeProvider>
            </AppRouterCacheProvider>
          </NextAppDirEmotionCacheProvider>
        </NextAppDirEmotionCacheProvider>
      </AppThemeContext.Provider>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};

export const useAppThemeContext =  () => useContext(AppThemeContext);
